;/*FB_PKG_DELIM*/

__d("DollyAccountContentWrapperWithPlaceholder.react",["MCDSFlexbox.react","MCDSSpinner.react","Placeholder.react","mcdsMargin","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u={fullSpaceContainer:{width:"xh8yej3",$$css:!0}};function c(e){var t=e.children,n=e.viewName,o=e.withMargin,a=o===void 0?!0:o;return s.jsx(r("Placeholder.react"),{fallback:s.jsx("div",{className:"x1mlu5p9 xg7mtoe xvc5jky x11t971q x2b8uid",children:s.jsx(r("MCDSSpinner.react"),{size:"large"})}),name:n,children:s.jsx(r("MCDSFlexbox.react"),{direction:"column",xstyle:[u.fullSpaceContainer,a&&r("mcdsMargin").responsive({vert:{tablet:40,mobile:24}})],children:t})})}c.displayName=c.name+" [from "+i.id+"]",l.default=c}),98);
__d("DollyAccountDevicesViewRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="32373600858919955"}),null);
__d("DollyAccountDigitalSubscriptionsViewRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="27312074575061239"}),null);
__d("DollyAccountPaymentMethodsViewRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="9578477752270361"}),null);
__d("DollyAccountQuestGalleryRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="24642120762065226"}),null);
__d("DollyAccountRedeemCodeViewRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="9943901422319970"}),null);
__d("DollyAccountSideNavigationContainerQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="27094959463421263"}),null);
__d("DollyAccountSideNavigationContainerQuery$Parameters",["DollyAccountSideNavigationContainerQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("DollyAccountSideNavigationContainerQuery_facebookRelayOperation"),metadata:{},name:"DollyAccountSideNavigationContainerQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("DollyAccountSideNavigationEntrypoint.entrypoint",["DollyAccountSideNavigationContainerQuery$Parameters","JSResourceForInteraction"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){return{queries:{queryReference:{parameters:r("DollyAccountSideNavigationContainerQuery$Parameters"),variables:{}}}}},root:r("JSResourceForInteraction")("DollyAccountSideNavigationContainer.react").__setRef("DollyAccountSideNavigationEntrypoint.entrypoint")};l.default=e}),98);
__d("DollyAccountViewRootDividerSpacingContext.react",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext({hideRightSpacing:!1,updateHideRightSpacing:function(){}});l.DollyAccountViewRootDividerSpacingContext=u}),98);
__d("DollyCMSMarketingOriginalPriceImplementation.react",["fbt","MCDSAccessibleElement.react","react"],(function(t,n,r,o,a,i,l,s){"use strict";var e,u=e||(e=o("react"));function c(e){var t=e.children;return u.jsxs("div",{className:"xmqliwb",children:[u.jsx(r("MCDSAccessibleElement.react"),{isHidden:!0,children:s._(/*BTDS*/"Original price")}),t]})}c.displayName=c.name+" [from "+i.id+"]",l.default=c}),226);
__d("DollyCMSMarketingOriginalPrice.react",["DollyCMSMarketingOriginalPriceImplementation.react","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsx(r("DollyCMSMarketingOriginalPriceImplementation.react"),babelHelpers.extends({},e))}u.displayName=u.name+" [from "+i.id+"]",l.default=u}),98);
__d("DollyDividerDirection",["$InternalEnum"],(function(t,n,r,o,a,i){var e=n("$InternalEnum")({HORIZONTAL:"horizontal",VERTICAL:"vertical"}),l=e;i.default=l}),66);
__d("MCDSVerticalDivider.react",["mcdsLineStyles","react","stylex","useMCDSColorScheme"],(function(t,n,r,o,a,i,l){"use strict";var e,s,u=s||(s=o("react")),c={root:{height:"x5yr21d",width:"x1i1rx1s",$$css:!0}};function d(t){var n=t.ref,o=t.xstyle,a=r("useMCDSColorScheme")();return u.jsx("div",babelHelpers.extends({ref:n},(e||(e=r("stylex"))).props(c.root,r("mcdsLineStyles")(a),o)))}d.displayName=d.name+" [from "+i.id+"]",l.default=d}),98);
__d("DollyDividerImplementation.react",["MCDSHorizontalDivider.react","MCDSVerticalDivider.react","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){var t=e.direction;switch(t){case"horizontal":return s.jsx(r("MCDSHorizontalDivider.react"),{});case"vertical":return s.jsx(r("MCDSVerticalDivider.react"),{})}}u.displayName=u.name+" [from "+i.id+"]",l.default=u}),98);
__d("DollyInlineInvoiceCTA.relayprovider",["gkx"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return r("gkx")("21406")}};l.default=e}),98);
__d("DollyWebEventElementType",["$InternalEnum"],(function(t,n,r,o,a,i){var e=n("$InternalEnum")({APP:"app",ARTICLE:"article",BANNER:"banner",BUTTON:"button",CARD:"card",CHECK_BOX:"check_box",COLOR_SWATCH:"color_swatch",DROPDOWN_LIST:"dropdown_list",FIELD:"field",FILTER_PANE:"filter_pane",FORUM_ARTICLE:"forum_article",GEN_AI_SOLUTION:"gen_ai_solution",HORIZONTAL_LIST:"horizontal_list",ICON:"icon",IMAGE:"image",LINK:"link",MODULE:"module",NEXT:"next",PREV:"prev",QUICK_FIX:"quick_fix",SELF_SERVE_SOLUTION:"self_serve_solution",TAB:"tab",TEXT:"text",VIDEO:"video"}),l=e;i.default=l}),66);
__d("MCDSCMSCommonDividerImplementation.react",["DollyDividerImplementation.react","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsx(r("DollyDividerImplementation.react"),{direction:e.direction})}u.displayName=u.name+" [from "+i.id+"]",l.default=u}),98);
__d("MCDSCMSCommonDivider.react",["MCDSCMSCommonDividerImplementation.react","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsx(r("MCDSCMSCommonDividerImplementation.react"),babelHelpers.extends({},e))}u.displayName=u.name+" [from "+i.id+"]",l.default=u}),98);
__d("SHOPEntOfferPriceProductOutOfStockBehaviorForCustomerEnum",[],(function(t,n,r,o,a,i){var e=Object.freeze({COMING_SOON:"COMING_SOON",NOT_AVAILABLE:"NOT_AVAILABLE",NOTIFY_ME:"NOTIFY_ME",OUT_OF_STOCK:"OUT_OF_STOCK"});i.default=e}),66);
__d("buildDollyAccountRoute.entrypoint",["DollyAccountSideNavigationEntrypoint.entrypoint","JSResourceForInteraction","NestedRelayEntryPointBuilderUtils","createMDCCommonCompoundEntryPointBuilder"],(function(t,n,r,o,a,i,l){"use strict";var e=r("JSResourceForInteraction")("DollyAccountViewRootBase.react").__setRef("buildDollyAccountRoute.entrypoint"),s=r("createMDCCommonCompoundEntryPointBuilder")(e,function(e){return{}},function(e){return{sideNavigationEntryPoint:o("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:n("DollyAccountSideNavigationEntrypoint.entrypoint"),entryPointParams:{}})}});l.default=s}),98);