;/*FB_PKG_DELIM*/

__d("DollyCMSMarketingProductVariantContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext({variant:null});l.default=u}),98);
__d("DollyCMSMarketingProductVariantContextProviderImplementation.react",["CometRouteParams","CometRouteURL","DollyCMSMarketingProductVariantContext","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e,c=u.useMemo,d=u.useSyncExternalStore;function m(e){return window.addEventListener("variantchange",e),window.addEventListener("popstate",e),function(){window.removeEventListener("variantchange",e),window.removeEventListener("popstate",e)}}function p(){var e=o("CometRouteURL").getWindowURLParams();if(e==null)return null;var t=e.variant;return t!=null?String(t):null}function _(){return null}function f(e){var t=e.children,n=o("CometRouteParams").useRouteParams(),a=n.variant,i=d(m,p,_),l=i!=null?i:a,u=c(function(){return{variant:l!=null?String(l):null}},[l]);return s.jsx(r("DollyCMSMarketingProductVariantContext").Provider,{value:u,children:t})}f.displayName=f.name+" [from "+i.id+"]",l.default=f}),98);
__d("DollyCMSMarketingProductVariantContextImplementation.react",["DollyCMSMarketingProductVariantContextProviderImplementation.react","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsx(r("DollyCMSMarketingProductVariantContextProviderImplementation.react"),babelHelpers.extends({},e))}u.displayName=u.name+" [from "+i.id+"]",l.default=u}),98);
__d("DollyCMSMarketingProductVariantContext.react",["DollyCMSMarketingProductVariantContextImplementation.react","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsx(r("DollyCMSMarketingProductVariantContextImplementation.react"),babelHelpers.extends({},e))}u.displayName=u.name+" [from "+i.id+"]",l.default=u}),98);
__d("useGalaxyDynamicContentContainer",["CometPlaceholder.react","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e.useRef;function c(e,t){return t===void 0&&(t=s.Fragment),u(e?function(e){var n=e.children;return s.jsx(t,{children:n})}:r("CometPlaceholder.react")).current}l.default=c}),98);
__d("DollyCMSMarketingProductVariantSpecificContentImplementation.react",["DollyCMSMarketingProductVariantContext","react","useGalaxyDynamicContentContainer"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e,c=u.useContext,d=u.useMemo;function m(e){var t=e.children,n=e.exclude,o=e.fallback,a=e.variants,i=c(r("DollyCMSMarketingProductVariantContext")),l=i.variant,u=d(function(){return n?l==null||!a.includes(l):l!=null&&a.includes(l)},[n,l,a]),m=r("useGalaxyDynamicContentContainer")(u);return u?s.jsx(m,{fallback:o,children:t}):null}m.displayName=m.name+" [from "+i.id+"]",l.default=m}),98);
__d("DollyCMSMarketingProductVariantSpecificContent.react",["DollyCMSMarketingProductVariantSpecificContentImplementation.react","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsx(r("DollyCMSMarketingProductVariantSpecificContentImplementation.react"),babelHelpers.extends({fallback:null},e))}u.displayName=u.name+" [from "+i.id+"]",l.default=u}),98);
__d("DollyTabClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1547"),s=o("FalcoLoggerInternal").create("dolly__tab__click",e),u=s;l.default=u}),98);
__d("DollyTabClickEvent.log",["DollyEventLoggerInternal","DollyTabClickFalcoEvent","identityFunction"],(function(t,n,r,o,a,i,l){"use strict";var e=o("DollyEventLoggerInternal").create({convertToHiveData:r("identityFunction"),hiveFalcoLogger:r("DollyTabClickFalcoEvent")});l.DollyTabClickEvent=e}),98);
__d("useGalaxyFormStringValue",["GalaxyScriptFormHandling","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.useCallback,c=s.useContext,d=s.useEffect,m=s.useMemo;function p(e,t){t===void 0&&(t="");var n=c(o("GalaxyScriptFormHandling").GalaxyScriptFormContext),r=n.fieldDefaults,a=n.fieldInputs,i=n.setFieldDefault,l=n.setFieldInput,s=n.submit;d(function(){i(e,t)},[t,e,i]);var p=m(function(){var n=a[e],o=r[e];return typeof n!="string"?String(o!=null?o:t):n},[t,r,a,e]),_=u(function(t){l(e,t)},[e,l]);return{value:p,onChange:_,onSubmit:s}}l.default=p}),98);