;/*FB_PKG_DELIM*/

__d("DollyBuyNowClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1541"),s=o("FalcoLoggerInternal").create("dolly__buy_now__click",e),u=s;l.default=u}),98);
__d("DollyCapiBuyNowFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1765"),s=o("FalcoLoggerInternal").create("dolly__capi__buy_now",e),u=s;l.default=u}),98);
__d("DollyBuyNowClickEvent.log",["DollyBuyNowClickFalcoEvent","DollyCapiBuyNowFalcoEvent","DollyEventLoggerInternal","DollyFBPixelEventNames","identityFunction"],(function(t,n,r,o,a,i,l){"use strict";function e(e){return{event_name:o("DollyFBPixelEventNames").DollyFBPixelEventNames.BuyNow,custom_data:Object.freeze({})}}function s(e){var t=e.category,n=e.product_name,r=e.sku;return{event_name:"click",custom_data:{category:t,sku:r,product_name:n,target_id:"buy_now.click"}}}var u=o("DollyEventLoggerInternal").create({convertToFBPixelData:e,convertToHiveData:r("identityFunction"),convertToTealiumData:s,hiveFalcoLogger:r("DollyBuyNowClickFalcoEvent"),fbPixelFalcoLogger:r("DollyCapiBuyNowFalcoEvent")});l.DollyBuyNowClickEvent=u}),98);
__d("DollyCustomizeClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("655"),s=o("FalcoLoggerInternal").create("dolly__customize__click",e),u=s;l.default=u}),98);
__d("DollyCustomizeClickEvent.log",["DollyCustomizeClickFalcoEvent","DollyEventLoggerInternal","identityFunction"],(function(t,n,r,o,a,i,l){"use strict";var e=o("DollyEventLoggerInternal").create({convertToHiveData:r("identityFunction"),hiveFalcoLogger:r("DollyCustomizeClickFalcoEvent")});l.DollyCustomizeClickEvent=e}),98);
__d("DollyCustomizeViewFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("7139"),s=o("FalcoLoggerInternal").create("dolly__customize__view",e),u=s;l.default=u}),98);
__d("DollyCustomizeViewEvent.log",["DollyCustomizeViewFalcoEvent","DollyEventLoggerInternal","identityFunction"],(function(t,n,r,o,a,i,l){"use strict";var e=o("DollyEventLoggerInternal").create({convertToHiveData:r("identityFunction"),hiveFalcoLogger:r("DollyCustomizeViewFalcoEvent")});l.DollyCustomizeViewEvent=e}),98);
__d("DollyMnmClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("191"),s=o("FalcoLoggerInternal").create("dolly__mnm__click",e),u=s;l.default=u}),98);
__d("DollyMnmClickEvent.log",["DollyEventLoggerInternal","DollyMnmClickFalcoEvent","identityFunction"],(function(t,n,r,o,a,i,l){"use strict";var e=o("DollyEventLoggerInternal").create({convertToHiveData:r("identityFunction"),hiveFalcoLogger:r("DollyMnmClickFalcoEvent")});l.DollyMnmClickEvent=e}),98);
__d("DollyNotifyMeClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1544"),s=o("FalcoLoggerInternal").create("dolly__notify_me__click",e),u=s;l.default=u}),98);
__d("DollyNotifyMeClickEvent.log",["DollyEventLoggerInternal","DollyNotifyMeClickFalcoEvent","identityFunction"],(function(t,n,r,o,a,i,l){"use strict";function e(e){var t=e.sku;return{event_name:"click",custom_data:{sku:t,target_id:"notify_me.click"}}}var s=o("DollyEventLoggerInternal").create({convertToHiveData:r("identityFunction"),convertToTealiumData:e,hiveFalcoLogger:r("DollyNotifyMeClickFalcoEvent")});l.DollyNotifyMeClickEvent=s}),98);
__d("DollyProductOptionSelectClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1545"),s=o("FalcoLoggerInternal").create("dolly__product_option__select__click",e),u=s;l.default=u}),98);
__d("DollyProductOptionSelectClickEvent.log",["DollyEventLoggerInternal","DollyProductOptionSelectClickFalcoEvent","identityFunction"],(function(t,n,r,o,a,i,l){"use strict";var e=o("DollyEventLoggerInternal").create({convertToHiveData:r("identityFunction"),hiveFalcoLogger:r("DollyProductOptionSelectClickFalcoEvent")});l.DollyProductOptionSelectClickEvent=e}),98);
__d("DollyRedirectCtaClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("35"),s=o("FalcoLoggerInternal").create("dolly__redirect_cta__click",e),u=s;l.default=u}),98);
__d("DollyRedirectCTAClickEvent.log",["DollyCapiGenericFalcoEvent","DollyEventLoggerInternal","DollyFBPixelEventNames","DollyRedirectCtaClickFalcoEvent","identityFunction","isFalsey"],(function(t,n,r,o,a,i,l){"use strict";function e(e){return{event_name:o("DollyFBPixelEventNames").DollyFBPixelEventNames.RedirectClick,custom_data:Object.freeze({content_ids:r("isFalsey")(e.sku)?[]:[e.sku]})}}function s(e){var t=e.category,n=e.sku;return{event_name:"click",custom_data:{category:t,sku:n,target_id:"buy_now.click"}}}var u=o("DollyEventLoggerInternal").create({convertToHiveData:r("identityFunction"),hiveFalcoLogger:r("DollyRedirectCtaClickFalcoEvent"),convertToTealiumData:s,convertToFBPixelData:e,fbPixelFalcoLogger:r("DollyCapiGenericFalcoEvent")});l.DollyRedirectCTAClickEvent=u}),98);
__d("MDCAIGlassesMixAndMatchBuyFlowContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext({colorFrameMap:new Map,currentPDPFrameColorGroup:null,currentProductOnPDP:null,defaultFrameColorProductID:null,defaultFrameColorProductSKU:null,defaultFrameColorShopCategory:null,frameColors:[],frameFirstClearLensMap:new Map,frameLensMap:new Map,initialFrameOfferID:null,initialLensOptionIDs:[],initialOfferIDs:[],lensOptionGroupMap:new Map,mixAndMatchFrames:[]});l.default=u}),98);